/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package game;

import java.util.Random;

/**
 *
 * @author Bhadresh
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    int stake;
    int market;
    int number;
    String Rindex;
    int tick_num;
    double ans = 0;
        
    public MainGUI() {
        initComponents();
        Tick_Result.setBorder(null);
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Currency = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Tick_Num = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Market = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        Stake = new javax.swing.JComboBox();
        Reset = new javax.swing.JButton();
        Go = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tick_Result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WANAIB TRADING");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Currency :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 83, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 61, 540, 14));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setText("Amout you wish to trade:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 32, 351, -1));

        Currency.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Currency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD" }));
        jPanel1.add(Currency, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 81, 71, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Stake      :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 132, 80, -1));

        Tick_Num.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Tick_Num.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel1.add(Tick_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 228, 71, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("I predict that the last decimal of 5th tick will NOT be :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 230, 340, -1));

        Market.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Market.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Random 50 Index", "Random 100 Index" }));
        jPanel1.add(Market, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 182, 150, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Market    :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 184, -1, -1));

        Stake.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Stake.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "60", "70", "80", "90", "100", "150", "200", "250", "300", "350", "400", "450", "500", "600", "700", "800", "900", "1000", " " }));
        jPanel1.add(Stake, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 130, 71, -1));

        Reset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 340, 70, 30));

        Go.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Go.setText("Go");
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        jPanel1.add(Go, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 280, 70, 30));

        jScrollPane1.setBorder(null);

        Tick_Result.setColumns(20);
        Tick_Result.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Tick_Result.setRows(10);
        Tick_Result.setBorder(null);
        jScrollPane1.setViewportView(Tick_Result);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 310, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
        // TODO add your handling code here:
        Tick_Result.setText(null);
        stake = Integer.parseInt(String.valueOf(Stake.getSelectedItem()));
        Rindex = String.valueOf(Market.getSelectedItem());
        tick_num = Integer.parseInt(String.valueOf(Tick_Num.getSelectedItem()));
        
        Random generator = new Random();
        
        for(int i=0;i<5;i++)
        {
            if(Rindex == "Random 50 Index")
                number = generator.nextInt(50);
            else
                number = generator.nextInt(100);
            double result = number / 1000.0;
            ans = result+number*number*number;
            int pos = Tick_Result.getCaretPosition(); //get the cursor position
            Tick_Result.insert(String.valueOf(ans)+"\n", pos);
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException ex)
            {
                Thread.currentThread().interrupt();
            }
            Tick_Result.update(Tick_Result.getGraphics());
        }
        
        String s = String.valueOf(ans);
        String s1 =  s.substring(s.length() - 1);
        
        if(Integer.parseInt(s1) == tick_num)
        {
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException ex)
            {
                Thread.currentThread().interrupt();
            }
            Tick_Result.update(Tick_Result.getGraphics());
            int pos = Tick_Result.getCaretPosition(); //get the cursor position
            Tick_Result.insert("\nSORRY ! YOUR PREDICTION WENT WRONG", pos);
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException ex)
            {
                Thread.currentThread().interrupt();
            }
            Go.doClick();
        }
        else
        {
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException ex)
            {
                Thread.currentThread().interrupt();
            }
            Tick_Result.update(Tick_Result.getGraphics());
            int pos = Tick_Result.getCaretPosition(); //get the cursor position
            Tick_Result.insert("\nYOUR ACCOUNT IS CREDITED WITH "+stake+" USD", pos);
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException ex)
            {
                Thread.currentThread().interrupt();
            }
            Go.doClick();
        }
        
    }//GEN-LAST:event_GoActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Stake.setSelectedIndex(0);
        Market.setSelectedIndex(0);
        Tick_Num.setSelectedIndex(0);
        Tick_Result.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Currency;
    private javax.swing.JButton Go;
    private javax.swing.JComboBox Market;
    private javax.swing.JButton Reset;
    private javax.swing.JComboBox Stake;
    private javax.swing.JComboBox Tick_Num;
    private javax.swing.JTextArea Tick_Result;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
